language: ruby
cache: bundler
rvm: 2.3.1
sudo: false
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  sonarcloud:
    organization: "jnieto1974-github" # the key of the org you chose at step #3
   
before_install:
 - gem install hiptest-publisher
 - hiptest-publisher -c rspec.conf  --test-run-id=211325 --only=tests

script:
 - bundle exec rspec --format RspecJunitFormatter -o report.xml
 - sonar-scanner
 
after_script:
  - hiptest-publisher -c rspec.conf  --push=report.xml --test-run-id=211325
  
